modLoader="javafml"
loaderVersion="[31,)"
[[mods]]
    modId="teamsmod"
    version="1.15.2-R2"
    displayName="Teams"
    credits="\nThanks to jabelar and Cadiboo's example mods for providing some guidance. Thanks to potat10125 for helping test things\n"
    authors="daPoseidonGuy\n"
    description='''
    Teams mod enables functional teams in minecraft encouraging social play

    Provides a GUI to see status of nearby teammates
    Provides advancement syncing, item transfer and other miscellaneous features

    '''
